"""utils/latex_export.py — publication-ready LaTeX tables from run results.

Generates booktabs-style tables matching the paper layout:

  Table 1 (overall):    Model | CQ CS RS LS ES SS | <aggregation strategies>
  Table 2 (per-dataset): Model | Dataset | CQ CS RS LS ES SS | Balanced

The best value in each numeric column is set in \\textbf{}. Output is a
single .tex file containing both tables inside table environments; copy the
tabular blocks directly into the manuscript, or \\input the file.
"""

import logging
from typing import Any, Dict, List

logger = logging.getLogger(__name__)

_METRIC_ORDER = [
    ("correctness",       "CQ"),
    ("consistency",       "CS"),
    ("robustness",        "RS"),
    ("logical_coherence", "LS"),
    ("efficiency",        "ES"),
    ("stability",         "SS"),
]


def _esc(s: str) -> str:
    return (str(s).replace("\\", r"\textbackslash{}").replace("&", r"\&")
            .replace("%", r"\%").replace("_", r"\_").replace("#", r"\#"))


def _fmt(v: Any, bold: bool = False) -> str:
    try:
        s = f"{float(v):.3f}"
    except (TypeError, ValueError):
        s = str(v)
    return f"\\textbf{{{s}}}" if bold else s


def _col_max(rows: List[List[float]], col: int) -> float:
    vals = [r[col] for r in rows if isinstance(r[col], (int, float))]
    return max(vals) if vals else float("nan")


def export_latex(results: List[Dict[str, Any]], path: str) -> str:
    """Write overall + per-dataset LaTeX tables for all completed models."""
    if not results:
        return ""

    # Aggregation strategy columns present in the results (stable order)
    agg_names: List[str] = []
    for r in results:
        for k in (r.get("aggregated") or {}):
            if k not in agg_names:
                agg_names.append(k)

    lines: List[str] = []
    lines.append("% Auto-generated by utils/latex_export.py — do not edit by hand.")
    lines.append("% Requires \\usepackage{booktabs}.")
    lines.append("")

    # ── Table 1: overall ────────────────────────────────────────────
    metric_cols = [m for m, _ in _METRIC_ORDER]
    rows = []
    for r in results:
        raw = r.get("raw_metrics", {})
        agg = r.get("aggregated", {})
        rows.append([r.get("model", "?")]
                    + [raw.get(m, float("nan")) for m in metric_cols]
                    + [agg.get(a, float("nan")) for a in agg_names])

    ncols = len(metric_cols) + len(agg_names)
    maxes = [_col_max([row[1:] for row in rows], c) for c in range(ncols)]

    agg_hdr = " & ".join(_esc(a.replace("_", " ").title()) for a in agg_names)
    lines += [
        "\\begin{table}[H]",
        "\\caption{Overall reasoning quality: raw metric scores and aggregated "
        "scores for all models.\\label{tab:overall}}",
        "\\centering",
        "\\begin{tabular}{l" + "c" * ncols + "}",
        "\\toprule",
        "\\textbf{Model} & " +
        " & ".join(f"\\textbf{{{abbr}}}" for _, abbr in _METRIC_ORDER) +
        (" & " + agg_hdr if agg_names else "") + " \\\\",
        "\\midrule",
    ]
    for row in rows:
        cells = [_esc(row[0])]
        for c, v in enumerate(row[1:]):
            bold = isinstance(v, (int, float)) and abs(v - maxes[c]) < 1e-9
            cells.append(_fmt(v, bold))
        lines.append(" & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]

    # ── Table 2: per-dataset breakdown ──────────────────────────────
    pd_rows = []
    for r in results:
        for ds_name in sorted((r.get("per_dataset") or {}).keys()):
            blk = r["per_dataset"][ds_name]
            raw = blk.get("raw_metrics", {})
            agg = blk.get("aggregated", {})
            pd_rows.append([r.get("model", "?"), ds_name]
                           + [raw.get(m, float("nan")) for m in metric_cols]
                           + [agg.get("balanced", float("nan"))])

    if pd_rows:
        n2 = len(metric_cols) + 1
        maxes2 = [_col_max([row[2:] for row in pd_rows], c) for c in range(n2)]
        lines += [
            "\\begin{table}[H]",
            "\\caption{Per-dataset metric breakdown for all model--dataset "
            "combinations.\\label{tab:perdataset}}",
            "\\centering",
            "\\begin{tabular}{ll" + "c" * n2 + "}",
            "\\toprule",
            "\\textbf{Model} & \\textbf{Dataset} & " +
            " & ".join(f"\\textbf{{{abbr}}}" for _, abbr in _METRIC_ORDER) +
            " & \\textbf{Balanced} \\\\",
            "\\midrule",
        ]
        prev_model = None
        for row in pd_rows:
            model = row[0]
            first = _esc(model) if model != prev_model else ""
            if model != prev_model and prev_model is not None:
                lines.append("\\midrule")
            prev_model = model
            cells = [first, _esc(row[1])]
            for c, v in enumerate(row[2:]):
                bold = isinstance(v, (int, float)) and abs(v - maxes2[c]) < 1e-9
                cells.append(_fmt(v, bold))
            lines.append(" & ".join(cells) + " \\\\")
        lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    logger.info(f"LaTeX tables saved: {path}")
    return path
